### ISSUE TITLE
Potential issue to warn in blog post

### ISSUE THREAD

**Issue by myShoggoth** [garry-cairns/ILikeWhenItWorks#1]
I tracked down the major issue I had to an incorrect source path in the -itv parameter, which either failed silently, did something disturbing, or did warn in a way I didn't at all notice.

Putting in a warning might save someone some trouble.

Much more minor - I didn't notice when you said to move to the site subdirectory at the beginning, and ended up redoing the stuff before that.  No biggie.

Finally, you may want to offer different instructions for those of us using boot2docker.  Mostly we don't need the sudo calls, but the other gotcha is that when things are up and running you need to run 'boot2docker ip' to find out what IP to connect the browser to, since it will be that ip:3000 and not localhost:3000.

Thank you for writing this up, it is a cool step for me for learning Docker (I've been working with Haskell/yesod for a few weeks now).

Next step for me is to figure out how to populate something like this Docker image with the custom version of shakespeare I'm working on but otherwise stock yesod.

**Comment by garry-cairns** [comment]
I've updated the blog post with a link to the boot2docker site and an appropriate warning re IP addresses. I've also tried to clarify when I move into the site directory at the beginning and warn about possible problems with -itv. Thanks again for raising this.

**Comment by myShoggoth** [comment]
Just saw the instructions for https://registry.hub.docker.com/u/jhedev/yesod-docker/ and I think the usage might be a bit more bullet proof by using pwd:

$ docker run -it -v `pwd`:/code jhedev/yesod-docker bash
